Fix #2
misterplus/LearnWithEase pull request #6
Opened 2021-04-22 03:16 UTC by misterplus

2021-04-22 03:51 UTC, debuggerzh commented
我在issue中的表述有歧义，实际上是appserver关闭时，客户端的提示有误

2021-04-22 03:52 UTC, debuggerzh requested changes
我在issue中的表述有歧义，实际上是appserver关闭时，客户端的提示有误

2021-04-22 03:58 UTC, misterplus commented
> 我在issue中的表述有歧义，实际上是appserver关闭时，客户端的提示有误

服务器异常是服务器关闭的状态描述，这样改动后提示是正确的。

2021-04-23 12:44 UTC, debuggerzh approved these changes

2021-04-23 12:44 UTC, merged